apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fluentd-py-api-svc
data:
  fluent.conf: |
    <source>
        @type tail
        path /app/logs/app.log
        pos_file /app/logs/app.log.pos
        tag app.logs
        <parse>
          @type grok
          <grok>
            pattern %{TIMESTAMP_ISO8601:timestamp} \| %{LOGLEVEL:level}\s*\| %{GREEDYDATA:message}
          </grok>
        </parse>
    </source>

    <filter app.logs>
      @type record_transformer
      <record>
        service_name "py-webhook-svc"
      </record>
    </filter>

    <match app.logs>
      @type bigquery_insert
      
      <buffer>
        flush_mode immediate
      </buffer>
      
      #auth_method compute_engine
      auth_method json_key
      json_key /app/gcp-key/fluentd-ingress-jason-hsbc.json
      # private_key_passphrase notasecret # default

      project jason-hsbc
      dataset LOGS
      auto_create_table true
      table py-api-logs

       <inject>
        time_key timestamp
        # time_type unixtime_millis # out of range
        time_type string
        time_format %Y-%m-%d %H:%M:%S.%L
      </inject>


      schema [
        {
          "name": "timestamp",
          "type": "TIMESTAMP"
        },
        {
          "name": "service_name",
          "type": "STRING"
        },
        {
          "name": "level",
          "type": "STRING"
        },
        {
          "name": "message",
          "type": "STRING"
        }
      ]
    </match>
