apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-webhook-svc
  labels:
    app: py-webhook-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-webhook-svc
  template:
    metadata:
      labels:
        app: py-webhook-svc
    spec:
      containers:
        - name: py-webhook-svc
          image: europe-west2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/py-webhook-svc:0.0.3
          ports:
            - containerPort: 8000
          volumeMounts: # write log here
            - name: volume-log
              mountPath: /app/logs/
              readOnly: false # read only is set to false


        - name: sidecar-fluentd
          image: europe-west2-docker.pkg.dev/jason-hsbc/my-docker-repo/fluentd-bigquery:1.0.1
          imagePullPolicy: Always
          command: ["sh"]
          args: 
            - "-c"
            - |
              fluentd -c /app/config/fluentd.conf

          volumeMounts: # read log from here
            - name: volume-log
              mountPath: /app/logs/
              readOnly: false # fluentd needs to write .pos file
            - name: config-volume
              mountPath: /app/config
              readOnly: true # read only is set to true




      volumes:
        - name: volume-log
          emptyDir: {}
        - name: config-volume
          configMap:
            name: configmap-fluentd-py-api-svc # name of the config map
            items:
              - key: fluent.conf # key of the config map item
                path: fluentd.conf # name of the file, it will only contain the content of the key


---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-py-webhook-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: py-webhook-svc # for the pods that have the label app: bq-api-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
